/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(diffenc_symgen.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3761b6a22421270e6250fabee740027c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rds/diffenc_symgen.h>
// pydoc.h is automatically generated in the build directory
#include <diffenc_symgen_pydoc.h>

void bind_diffenc_symgen(py::module& m)
{

    using diffenc_symgen    = gr::rds::diffenc_symgen;


    py::class_<diffenc_symgen, gr::block, gr::basic_block,
        std::shared_ptr<diffenc_symgen>>(m, "diffenc_symgen", D(diffenc_symgen))

        .def(py::init(&diffenc_symgen::make),
           D(diffenc_symgen,make)
        )
        



        ;




}








